### ISSUE TITLE
Grounding UPF problems

### ISSUE THREAD

**Issue by fteicht** [aiplan4eu/up-skdecide#1]
Need for figuring out how to ground UPF problems, especially to wrap them into scikit-decide domains.
TODOs as per the TODO lines in the [scikit-decide domain wrapper](https://github.com/aiplan4eu/skdecide-upf/blob/05432c7a01552a0cc36c9c84966fa2bb8e349522/upf_skdecide/domain.py):

- how to get instantiated actions' rewards or costs?
- how to get instantiated parameters of actions whose preconditions hold in a given state (i.e. assignments)?
- how to get all the possible instantiated actons?

**Comment by fteicht** [comment]
Hi @mikand I think I will need your help for this. Maybe we should organize a 1h meeting to work this out? Thanks

**Comment by mikand** [comment]
Hi @fteicht,

here are some comments (to be discussed if needed).

- Indeed, we need to ground the problem upfront in order to handle the action parameters (doing it online inside the `Domain` seems a waste of computational resources because you would need to re-ground the same actions over and over). The UPF will soon offer this service, but in the meantime you can simply assume (and assert) that all the actions have no parameters. This should simplify your code, because the action space simply becomes the list of the problem actions (not action instances) and the `_get_applicable_actions_from` method also returns a subset of the actions (those applicable in the given state). Note that there is no need to create action instances at this point, you can reason at the level of actions. Once a policy is generated by a RL, we can follow it to (possibly) retrieve a plan made of action instances.
- The semantics of the `for` loop at line 95 seems wrong: all the action preconditions must hold, while you seem to add the action if at least one precondition holds. 
- Concerning the reward, we will soon have a plan quality measure that will allow to give a meaningful reward, but for the time being you can set 0 for every transitions except for the ones reaching a goal state that can get 1. Does this make sense?

**Comment by fteicht** [comment]
Related to [this comment](https://github.com/aiplan4eu/unified-planning/issues/113#issuecomment-1082880685).

**Comment by fteicht** [comment]
@mikand The second item in [your](https://github.com/aiplan4eu/up-skdecide/issues/1#issuecomment-973014850) comment is fixed in [this](https://github.com/aiplan4eu/up-skdecide/commit/89e55e3bad16b627369513e256dc847612661ca0) commit. We can close the issue. Thanks!
